import re
cf_rule = {
    0 : {
        "A": 0,
        "0": 0,
        "B": 1,
        "1": 1,
        "C": 2,
        "2": 2,
        "D": 3,
        "3": 3,
        "E" : 4,     
        "4" : 4,
        "F" : 5,   
        "5": 5, 
        "G" : 6,     
        "6": 6, 
        "H" : 7,     
        "7": 7,
        "I" : 8,     
        "8": 8, 
        "J" : 9,     
        "9" : 9,
        "K" : 10, 
        "L" : 11,
        "M" : 12,
        "N" : 13,
        ":" : 14,
        "P" : 15,
        "Q" : 16,
        "R" : 17,
        "S" : 18,
        "T" : 19,
        "U" : 20,
        "V" : 21,
        "W" : 22,
        "X" : 23,
        "Y" : 24,
        "Z" : 25,
    },
    1:{
        "A" : 1,
        "0" : 1,
        "B" : 0,
        "1" : 0,
        "C" : 5,
        "2" : 5,
        "D" : 7,
        "3" : 7,
        "E" : 9,
        "4" : 9,
        "F" : 13,
        "5" : 13,
        "G" : 15,
        "6" : 15,
        "H" : 17,
        "7" : 17,
        "I" : 19,
        "8" : 19,
        "J" : 21,
        "9" : 21,
        "K" : 2,
        "L" : 4,
        "M" : 18,
        "N" : 20,
        "O" : 11,
        "P" : 3,
        "Q" : 6,
        "R" : 8,
        "S" : 12,
        "T" : 14,
        "U" : 16,
        "V" : 10,
        "W" : 22,
        "X" : 25,
        "Y" : 24,
        "Z" : 23,
    },
    "check":{
        0 : "A",
        1 : "B",
        2 : "C",
        3 : "D",
        4 : "E",
        5 : "F",
        6 : "G",
        7 : "H",
        8 : "I",
        9 : "J",
        10 : "K",
        11 : "L",
        12 : "M",
        13 : "N",
        14 : "O",
        15 : "P",
        16 : "Q",
        17 : "R",
        18 : "S",
        19 : "T",
        20 : "U",
        21 : "V",
        22 : "W",
        23 : "X",
        24 : "Y",
        25 : "Z",
    }
}


def check_codice_fiscale(codice:str)->bool:
    regex = re.compile("^[A-Za-z]{6}[0-9]{2}[A-Za-z]{1}[0-9]{2}[A-Za-z]{1}[0-9]{3}[A-Za-z]{1}$")
    if regex.match(codice):
        sum = 0
        for i in range(0,15):
            sum += cf_rule[(i+1)%2][codice[i]]
        return cf_rule["check"][sum%26] == codice[15]
    return False

def reset_prenotazione(user_data:dict):
    possible_keys = ["durata","servizi","chose","chosing","second_chose","sedi","session","token","date","ora","avaliable_times"]
    for k in possible_keys:
        if k in user_data:
            del user_data[k]